### ISSUE TITLE
Add correct capabilites

### ISSUE THREAD

**Issue by Nullmann** [eLearning-TUDarmstadt/moodle-tool_supporter#12]
give different roles the permission to only read/read and write

Useful for 1st level support

**Comment by Nullmann** [comment]
See:
https://docs.moodle.org/dev/Access_API

**Comment by Nullmann** [comment]
Maybe it is sufficient if there are only two contexts: read and write

**Comment by SteffenPegenau** [comment]
Please remember that a user needs a certain capability to do/see something and that a role is only a configurable set of capabilities. 

Try to reuse the capabilities Moodle is shipped with. So that a user can see or edit what she/he can see or edit in Moodle. 
Try to avoid creating new capabilities. Use for example a capability like core/course:can_enrol instead of tool/supporter:user_can _ enrol
(To avoid cloning every single core capability ;) )
